// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookstore.Data;

#nullable disable

namespace OnlineBookstore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613092050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineBookstore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OnlineBookstore.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "F. Scott Fitzgerald",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4694),
                            Description = "A story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
                            ISBN = "9780743273565",
                            ImageUrl = "/images/books/gatsby.jpg",
                            Price = 10.99m,
                            StockQuantity = 50,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "George Orwell",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4703),
                            Description = "A dystopian social science fiction novel and cautionary tale about the future.",
                            ISBN = "9780451524935",
                            ImageUrl = "/images/books/1984.jpg",
                            Price = 9.99m,
                            StockQuantity = 75,
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Frank Herbert",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4706),
                            Description = "Set on the desert planet Arrakis, a mix of politics, religion, and power.",
                            ISBN = "9780441013593",
                            ImageUrl = "/images/books/dune.jpg",
                            Price = 12.99m,
                            StockQuantity = 60,
                            Title = "Dune"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Douglas Adams",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4707),
                            Description = "A comedy science fiction series about the adventures of Arthur Dent.",
                            ISBN = "9780345391803",
                            ImageUrl = "/images/books/hitchhiker.jpg",
                            Price = 8.99m,
                            StockQuantity = 40,
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Stieg Larsson",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4709),
                            Description = "A psychological thriller about a journalist and a hacker investigating a disappearance.",
                            ISBN = "9780307949486",
                            ImageUrl = "/images/books/dragon-tattoo.jpg",
                            Price = 11.99m,
                            StockQuantity = 45,
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Gillian Flynn",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4711),
                            Description = "A thriller about a marriage gone terribly wrong.",
                            ISBN = "9780307588371",
                            ImageUrl = "/images/books/gone-girl.jpg",
                            Price = 10.99m,
                            StockQuantity = 55,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Jane Austen",
                            CategoryId = 4,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4712),
                            Description = "A romantic novel following the character development of Elizabeth Bennet.",
                            ISBN = "9780141439518",
                            ImageUrl = "/images/books/pride-prejudice.jpg",
                            Price = 7.99m,
                            StockQuantity = 80,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Nicholas Sparks",
                            CategoryId = 4,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4715),
                            Description = "A touching love story that spans decades.",
                            ISBN = "9780553816716",
                            ImageUrl = "/images/books/notebook.jpg",
                            Price = 9.99m,
                            StockQuantity = 65,
                            Title = "The Notebook"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Robert C. Martin",
                            CategoryId = 5,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4741),
                            Description = "A Handbook of Agile Software Craftsmanship.",
                            ISBN = "9780132350884",
                            ImageUrl = "/images/books/clean-code.jpg",
                            Price = 42.99m,
                            StockQuantity = 30,
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Gang of Four",
                            CategoryId = 5,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4743),
                            Description = "Elements of Reusable Object-Oriented Software.",
                            ISBN = "9780201633610",
                            ImageUrl = "/images/books/design-patterns.jpg",
                            Price = 54.99m,
                            StockQuantity = 25,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            BookId = 11,
                            Author = "Eric Ries",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4744),
                            Description = "How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses.",
                            ISBN = "9780307887894",
                            ImageUrl = "/images/books/lean-startup.jpg",
                            Price = 16.99m,
                            StockQuantity = 40,
                            Title = "The Lean Startup"
                        },
                        new
                        {
                            BookId = 12,
                            Author = "Peter Thiel",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4746),
                            Description = "Notes on Startups, or How to Build the Future.",
                            ISBN = "9780804139298",
                            ImageUrl = "/images/books/zero-to-one.jpg",
                            Price = 18.99m,
                            StockQuantity = 35,
                            Title = "Zero to One"
                        },
                        new
                        {
                            BookId = 13,
                            Author = "Stephen Hawking",
                            CategoryId = 7,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4747),
                            Description = "From the Big Bang to Black Holes.",
                            ISBN = "9780553380163",
                            ImageUrl = "/images/books/brief-history.jpg",
                            Price = 13.99m,
                            StockQuantity = 50,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            BookId = 14,
                            Author = "Richard Dawkins",
                            CategoryId = 7,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4749),
                            Description = "A book on evolution and genetics from the gene-centered view.",
                            ISBN = "9780199291151",
                            ImageUrl = "/images/books/selfish-gene.jpg",
                            Price = 14.99m,
                            StockQuantity = 45,
                            Title = "The Selfish Gene"
                        },
                        new
                        {
                            BookId = 15,
                            Author = "Yuval Noah Harari",
                            CategoryId = 8,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4751),
                            Description = "A Brief History of Humankind.",
                            ISBN = "9780062316097",
                            ImageUrl = "/images/books/sapiens.jpg",
                            Price = 15.99m,
                            StockQuantity = 70,
                            Title = "Sapiens"
                        },
                        new
                        {
                            BookId = 16,
                            Author = "Sun Tzu",
                            CategoryId = 8,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4752),
                            Description = "An ancient Chinese military treatise.",
                            ISBN = "9781599869773",
                            ImageUrl = "/images/books/art-of-war.jpg",
                            Price = 6.99m,
                            StockQuantity = 90,
                            Title = "The Art of War"
                        },
                        new
                        {
                            BookId = 17,
                            Author = "James Clear",
                            CategoryId = 9,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4754),
                            Description = "An Easy & Proven Way to Build Good Habits & Break Bad Ones.",
                            ISBN = "9780735211292",
                            ImageUrl = "/images/books/atomic-habits.jpg",
                            Price = 17.99m,
                            StockQuantity = 85,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            BookId = 18,
                            Author = "Stephen Covey",
                            CategoryId = 9,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4755),
                            Description = "Powerful Lessons in Personal Change.",
                            ISBN = "9781982137274",
                            ImageUrl = "/images/books/7-habits.jpg",
                            Price = 14.99m,
                            StockQuantity = 60,
                            Title = "The 7 Habits of Highly Effective People"
                        },
                        new
                        {
                            BookId = 19,
                            Author = "J.K. Rowling",
                            CategoryId = 10,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4758),
                            Description = "The first book in the Harry Potter series.",
                            ISBN = "9780590353427",
                            ImageUrl = "/images/books/harry-potter.jpg",
                            Price = 11.99m,
                            StockQuantity = 100,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            BookId = 20,
                            Author = "E.B. White",
                            CategoryId = 10,
                            CreatedDate = new DateTime(2026, 6, 13, 9, 20, 46, 75, DateTimeKind.Utc).AddTicks(4759),
                            Description = "A children's novel about a pig named Wilbur and his friendship with a spider.",
                            ISBN = "9780064400558",
                            ImageUrl = "/images/books/charlottes-web.jpg",
                            Price = 8.99m,
                            StockQuantity = 70,
                            Title = "Charlotte's Web"
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartItemId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineBookstore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Novels, stories, and imaginative literature",
                            Name = "Fiction"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Futuristic and speculative fiction",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Suspenseful and mysterious stories",
                            Name = "Mystery & Thriller"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Love stories and romantic fiction",
                            Name = "Romance"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Programming, computing, and tech books",
                            Name = "Technology"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Business, management, and entrepreneurship",
                            Name = "Business"
                        },
                        new
                        {
                            CategoryId = 7,
                            Description = "Scientific discoveries and research",
                            Name = "Science"
                        },
                        new
                        {
                            CategoryId = 8,
                            Description = "Historical events and biographies",
                            Name = "History"
                        },
                        new
                        {
                            CategoryId = 9,
                            Description = "Personal development and self-improvement",
                            Name = "Self-Help"
                        },
                        new
                        {
                            CategoryId = 10,
                            Description = "Books for young readers",
                            Name = "Children's Books"
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineBookstore.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("OnlineBookstore.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnlineBookstore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookstore.Models.Book", b =>
                {
                    b.HasOne("OnlineBookstore.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineBookstore.Models.CartItem", b =>
                {
                    b.HasOne("OnlineBookstore.Models.Book", "Book")
                        .WithMany("CartItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Models.ApplicationUser", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookstore.Models.Order", b =>
                {
                    b.HasOne("OnlineBookstore.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookstore.Models.OrderDetail", b =>
                {
                    b.HasOne("OnlineBookstore.Models.Book", "Book")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineBookstore.Models.Review", b =>
                {
                    b.HasOne("OnlineBookstore.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Models.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineBookstore.Models.ApplicationUser", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("OnlineBookstore.Models.Book", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("OnlineBookstore.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OnlineBookstore.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
